import React, { createContext, useContext, useState, useEffect } from 'react';

interface Translations {
  [key: string]: {
    [key: string]: string;
  };
}

const translations: Translations = {
  ko: {
    'nav.features': '특징',
    'nav.technology': '기술',
    'nav.about': 'About',
    'nav.contact': '문의하기',
    'nav.buy': '구매하기',
    'hero.title': 'PUTTIST II',
    'hero.subtitle': '디지털 퍼팅 연습의 새로운 기준',
    'hero.description': '기존 퍼팅 매트와는 다른 과학적 훈련 시스템. 레이저 가이드 기술로 20m 거리와 1m 폭을 정밀하게 측정합니다.',
    'hero.learn_more': '자세히 알아보기',
    'hero.watch_demo': '데모 보기',
    'share.kakao': '카카오톡 공유',
    'countdown.title': '박람회 특별 할인 진행중',
    'countdown.label': '남은 시간:',
    'countdown.days': '일',
    'countdown.hours': '시간',
    'countdown.minutes': '분',
    'countdown.seconds': '초',
    'countdown.discount': '10% 추가 할인',
    'form.title': '무료 체험 신청하기',
    'form.subtitle': '박람회 방문자 특별 혜택! 지금 신청하시면 ',
    'form.subtitle_highlight': '10% 할인 쿠폰',
    'form.subtitle_end': '을 드립니다',
    'form.name': '이름 *',
    'form.email': '이메일 *',
    'form.phone': '연락처 *',
    'form.purpose': '사용 목적',
    'form.purpose_personal': '개인 연습용',
    'form.purpose_business': '업체 구매',
    'form.purpose_school': '학교/교육기관',
    'form.purpose_golf': '골프장/연습장',
    'form.interest': '관심 정보 (복수 선택 가능)',
    'form.interest_discount': '할인 정보',
    'form.interest_catalog': '카탈로그 받기',
    'form.interest_demo': '무료 체험 신청',
    'form.interest_newsletter': '뉴스레터 구독',
    'form.message': '문의사항',
    'form.privacy': '개인정보 수집 및 이용에 동의합니다',
    'form.submit': '✨ 신청하기',
    'form.success': '✅ 신청이 완료되었습니다! 곧 연락드리겠습니다.',
    'about.title': 'PUTTIST 이야기',
    'about.origin_title': '어디서 시작되었나',
    'about.origin_text': 'PUTTIST는 2010년 전설적인 Dave Pelz의 "The Putting Bible"을 읽고 시작되었습니다. 그 중 한 부분이 특히 눈에 띄었습니다: 거리 조절의 중요성—그 하나의 기술을 마스터하는 것이 당신의 게임을 완전히 바꿀 수 있다는 것입니다. 그 아이디어가 하나의 미션을 촉발시켰습니다: 전 세계 아마추어 골퍼들을 위해 고품질 퍼팅 연습을 더 쉽고 접근하기 쉽게 만드는 것입니다.',
    'about.philosophy_title': '디지털 퍼팅 미터',
    'about.philosophy_text': 'PUTTIST는 디지털 퍼팅 연습기가 아닌 디지털 "퍼팅 미터"입니다. 우리는 "퍼팅 연습은 실제 그린에서 해야 한다"는 고정관념을 재정의합니다. 매 순간 그린 스피드가 변하는 실제 그린에서의 연습은 어렵고 시간이 많이 드는 고전적인 방법입니다. PUTTIST와 함께라면 집에서, 사무실에서, 언제 어디서나 투어 레벨의 퍼팅 연습이 가능합니다.',
    'about.core_concept_title': '20개의 퍼터를 가진 것처럼',
    'about.core_concept_text': 'PUTTIST의 궁극적인 목표는 20미터까지 1m 단위로 20개의 표준 퍼팅 거리감을 근육에 저장하는 것입니다. 이 정도의 연습량이 되면 항상 똑바로 퍼팅하고 일관된 터치가 저절로 만들어집니다. 마치 스스로가 20개의 퍼터를 가지고 있는 것처럼 되어 원하는 퍼팅 거리에서 맘대로 꺼내어 사용하기만 하면 됩니다. 아이언 플레이와 유사하죠? 이를 위해서는 무수한 연습이 필요합니다. 이 정도의 연습량은 실제 그린에서는 물론 다른 퍼팅 연습기에서는 불가능한 목표일 수도 있습니다. PUTTIST는 즉시 사용이 쉬우며 공 하나로 연습을 반복할 수 있기 때문입니다.',
    'about.innovation_title': 'PUTTIST II의 혁신',
    'about.feature1_title': '프리미엄 화이트 디자인',
    'about.feature1_desc': '고급스러운 화이트 바디와 디스플레이로 새롭게 태어난 PUTTIST',
    'about.feature2_title': '레이저 기능 강화',
    'about.feature2_desc': 'LASER READY 기능으로 방향 연습을 한층 더 강화',
    'about.feature3_title': '20미터로 확장',
    'about.feature3_desc': '15미터에서 20미터로 측정 거리 확장. 이제 20미터 3퍼팅도 해결!',
    'about.feature4_title': 'USB C-타입 충전',
    'about.feature4_desc': '전용 충전기 대신 USB C-타입 사용. 충전기가 고장나도 괜찮아요!',
    'about.feature5_title': '9개 랜덤 미션',
    'about.feature5_desc': '20미터까지 9개의 랜덤 미션 추가. 최고 난이도의 도전!',
    'about.feature6_title': '집에서 60피트 연습',
    'about.feature6_desc': '공 하나로 거실에서 60피트 롱 퍼팅 연습 가능. 볼 리턴 불필요!',
    'features.title': '핵심 기능',
    'features.subtitle': '프로 수준의 퍼팅 훈련을 집에서',
    'features.distance_title': '20m 거리 측정',
    'features.distance_desc': '최대 20미터까지 정밀한 거리 측정이 가능합니다. 실제 필드와 동일한 환경에서 훈련하세요.',
    'features.width_title': '1m 폭 측정',
    'features.width_desc': '1미터 폭까지 정확하게 감지합니다. 정확도 향상을 위한 즉각적인 피드백을 받으세요.',
    'features.portable_title': '휴대 편의성',
    'features.portable_desc': '언제 어디서나 간편하게 설치하고 사용할 수 있습니다. 집, 사무실, 야외 어디든 가능합니다.',
    'technology.title': '기존 퍼팅 매트와 다른 과학적 훈련',
    'technology.subtitle': '레이저 가이드 기술로 완벽한 퍼팅을 완성하세요',
    'technology.precision_title': '✨ 레이저 정밀도',
    'technology.precision_desc': '첨단 레이저 기술로 밀리미터 단위까지 정확한 측정',
    'technology.data_title': '📊 데이터 분석',
    'technology.data_desc': '모든 퍼팅 데이터를 기록하고 분석하여 실력 향상 추적',
    'technology.feedback_title': '🎯 즉각 피드백',
    'technology.feedback_desc': '실시간으로 퍼팅 결과를 확인하고 즉시 교정',
    'technology.pro_title': '🏆 프로 훈련',
    'technology.pro_desc': '프로 골퍼들이 사용하는 과학적 훈련 방법',
    'demo.title': '동영상으로 보는 PUTTIST II',
    'demo.subtitle': '제품 사용 방법과 특징을 영상으로 확인하세요',
    'cta.title': '지금 PUTTIST II와 함께 퍼팅 실력을 향상시키세요',
    'cta.subtitle': '프로 수준의 훈련을 집에서 시작하세요',
    'cta.button_naver': '지금 구매하기 (네이버)',
    'cta.button_amazon': 'Amazon에서 구매',
    // FAQ Section
    'faq.title': '자주 묻는 질문',
    'faq.subtitle': 'PUTTIST II에 대해 궁금한 점을 확인하세요',
    'faq.q1': 'PUTTIST II는 어떤 제품인가요?',
    'faq.a1': 'PUTTIST II는 레이저 가이드 기술을 활용한 디지털 퍼팅 미터입니다. 일반 퍼팅 매트와 달리 20m 거리와 1m 폭을 정밀하게 측정하여 집에서도 프로처럼 퍼팅 연습을 할 수 있습니다. 핵심은 20미터까지 1m 단위로 20개의 표준 거리감을 근육에 저장하는 것입니다. 마치 20개의 퍼터를 가진 것처럼, 원하는 거리를 선택해서 사용할 수 있게 됩니다. 이는 아이언 플레이와 유사한 개념으로, 실전 그린보다 먼저 선행 학습해야 하는 필수 훈련 시스템입니다. 공 하나로 무한 반복 연습이 가능하며, 실제 그린이나 다른 연습기에서는 불가능한 연습량을 달성할 수 있습니다.',
    'faq.q2': '집에서 사용하기 좋은 퍼팅 연습기는?',
    'faq.a2': 'PUTTIST II를 강력히 추천합니다. 기존 퍼팅 매트는 단순 보조 장비였지만, PUTTIST II는 실전 그린보다 반드시 먼저 학습해야 하는 필수 훈련 도구입니다. 20m 거리 측정, 레이저 가이드, USB-C 충전, 9가지 랜덤 미션으로 효과적인 실내 퍼팅 연습이 가능합니다. 특히 공 하나만으로 볼 리턴 없이 거실에서 60피트 롱 퍼팅까지 연습할 수 있어, 실제 그린에서는 불가능한 수준의 반복 훈련이 가능합니다. 매트가 짧은 이유도 바로 여기에 있습니다 - 즉시 사용이 쉽고 공 하나로 무한 반복할 수 있기 때문입니다.',
    'faq.q3': 'PUTTIST II 가격은 얼마인가요?',
    'faq.a3': 'PUTTIST II 고급형은 199,000원, 일반형은 159,000원입니다. 네이버 스마트스토어(smartstore.naver.com/3puttkiller)에서 구매 가능하며 전국 무료 배송이 제공됩니다. 고급형과 일반형의 주요 차이는 디스플레이와 마감 품질이며, 핵심 기능인 20m 거리 측정, 레이저 가이드, 9가지 랜덤 미션은 동일합니다. 30일 만족 보장 제도를 운영하고 있어 제품이 마음에 들지 않으시면 30일 내 100% 환불해 드립니다. 또한 1년 무상 AS를 제공하여 안심하고 사용하실 수 있습니다.',
    'faq.q4': '퍼팅 실력 향상에 효과가 있나요?',
    'faq.a4': '네, 매우 효과적입니다. PUTTIST II의 핵심 철학은 20미터까지 1m 단위로 20개의 표준 퍼팅 거리감을 근육에 저장하는 것입니다. 레이저 가이드로 정확한 방향을 잡고, 거리 측정 기능으로 일관된 스트로크를 연습할 수 있습니다. 이 정도의 연습량이 되면 항상 똑바로 퍼팅하고 일관된 터치가 저절로 만들어지기 때문에, 처음에는 퍼팅이 똑바로 가든 안 가든, 터치가 좋든 나쁘든 상관없습니다. 무수한 연습을 통해 자연스럽게 실력이 향상됩니다. 실제 그린이나 다른 연습기에서는 달성하기 어려운 연습량을 PUTTIST로 쉽게 달성할 수 있습니다.',
    'faq.q5': '설치가 어렵지 않나요?',
    'faq.a5': '전혀 어렵지 않습니다. 설치가 필요 없고 박스에서 꺼내 전원만 켜면 바로 사용할 수 있습니다. 이것이 PUTTIST의 핵심 장점 중 하나로, 즉시 사용이 쉬워 공 하나로 무한 반복 연습이 가능합니다. USB-C 충전 방식으로 4시간 충전 시 약 1개월 사용 가능하며, 전용 충전기가 아닌 일반 USB-C 케이블을 사용하기 때문에 충전기가 고장나도 걱정 없습니다. 휴대도 간편해서 집, 사무실, 야외 어디든 가지고 다니며 연습할 수 있습니다.',
    'faq.q6': '초보자도 사용할 수 있나요?',
    'faq.a6': '네, 초보자에게 특히 강력히 추천합니다. 레이저 가이드 라인이 정확한 퍼팅 방향을 시각적으로 보여주고, 거리 측정 기능이 실시간 피드백을 제공하기 때문에 올바른 습관을 처음부터 형성할 수 있습니다. PUTTIST는 실전 그린보다 먼저 선행 학습해야 하는 필수 코스이므로, 초보자일수록 빨리 시작하는 것이 좋습니다. 9가지 랜덤 미션은 난이도별로 구성되어 있어 실력에 맞게 단계적으로 연습할 수 있으며, 게임처럼 즐기면서 자연스럽게 퍼팅 실력이 향상됩니다. 처음에는 방향과 터치가 부정확해도 괜찮습니다 - 반복 연습이 자동으로 교정해줍니다.',
    'faq.q7': '아파트에서 사용해도 시끄럽지 않나요?',
    'faq.a7': '전혀 시끄럽지 않습니다. PUTTIST II는 정숙 설계로 층간 소음 걱정 없이 사용할 수 있습니다. 실제 퍼팅 매트 위에서 조용히 연습하실 수 있으며, 볼 리턴 장치가 없어 굴러가는 소음도 없습니다. 공 하나로 짧은 매트에서 반복 연습하는 방식이기 때문에 소음이 발생할 이유가 없습니다. 밤늦은 시간이나 새벽에도 가족이나 이웃에게 방해 없이 연습할 수 있어, 바쁜 직장인들도 퇴근 후 편하게 사용하고 있습니다.',
    'faq.q8': '배송은 얼마나 걸리나요?',
    'faq.a8': '주문 후 2-3일 내 전국 무료 배송됩니다. 네이버 스마트스토어(smartstore.naver.com/3puttkiller)에서 주문 시 실시간 배송 추적이 가능하며, 카카오톡이나 문자로 배송 알림을 받을 수 있습니다. 제주도 및 도서산간 지역도 무료 배송이며, 다만 1-2일 정도 추가 소요될 수 있습니다. 배송은 안전한 포장으로 진행되며, 제품 수령 후 즉시 사용 가능합니다. 별도의 설치나 조립이 필요 없어 받자마자 바로 연습을 시작할 수 있습니다.',
    'faq.q9': '환불이나 반품이 가능한가요?',
    'faq.a9': '30일 만족 보장 제도를 운영하고 있습니다. 제품에 만족하지 않으시면 30일 내 100% 환불해 드립니다. 단순 변심도 가능하며, 반품 배송비는 고객 부담입니다. 제품 불량이나 오배송의 경우 반품 배송비도 당사가 부담합니다. PUTTIST는 실전 그린보다 먼저 선행 학습해야 하는 새로운 방법론을 제시하기 때문에, 구매 여부에 상관없이 체험해보시길 권장합니다. 30일 동안 충분히 사용해보시고 결정하세요.',
    'faq.q10': 'AS는 어떻게 받나요?',
    'faq.a10': '1년 무상 AS를 제공합니다. 고객센터(010-1234-5678)로 연락하시거나 네이버 스마트스토어 문의 게시판을 이용하시면 신속하게 처리해 드립니다. 일반적인 고장은 택배 왕복 AS로 진행되며, 센서나 레이저 관련 문제는 대부분 원격 안내로 해결 가능합니다. USB-C 충전 방식이라 충전기 고장 걱정도 없고, 내구성이 뛰어나 오래 사용하실 수 있습니다. AS 기간 이후에도 합리적인 비용으로 유상 수리를 제공합니다.',
    // Comparison Section
    'comparison.title': 'PUTTIST II vs 기존 방식',
    'comparison.subtitle': '왜 PUTTIST II가 다른가요?',
    'comparison.feature': '비교 항목',
    'comparison.traditional_mat': '일반 퍼팅 매트',
    'comparison.real_green': '실제 그린',
    'comparison.distance_measurement': '거리 측정',
    'comparison.laser_guide': '레이저 가이드',
    'comparison.practice_volume': '연습량',
    'comparison.convenience': '편의성',
    'comparison.data_feedback': '데이터 피드백',
    'comparison.cost': '비용',
    'comparison.summary_title': 'PUTTIST II만의 차별점',
    'comparison.summary_text': 'PUTTIST II는 실전 그린보다 먼저 선행 학습해야 하는 필수 훈련 시스템입니다. 20미터까지 1m 단위로 20개의 표준 거리감을 근육에 저장하여 마치 20개의 퍼터를 가진 것처럼 만들어줍니다. 공 하나로 무한 반복 연습이 가능하며, 실제 그린이나 다른 연습기에서는 불가능한 연습량을 달성할 수 있습니다.'
  },
  en: {
    'nav.features': 'Features',
    'nav.technology': 'Technology',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.buy': 'Buy Now',
    'hero.title': 'PUTTIST II',
    'hero.subtitle': 'The New Standard in Digital Putting Practice',
    'hero.description': 'A scientific training system unlike traditional putting mats. Precisely measures 20m distance and 1m width with laser guide technology.',
    'hero.learn_more': 'Learn More',
    'hero.watch_demo': 'Watch Demo',
    'share.kakao': 'Share on KakaoTalk',
    'countdown.title': 'Expo Special Discount',
    'countdown.label': 'Time Remaining:',
    'countdown.days': 'Days',
    'countdown.hours': 'Hours',
    'countdown.minutes': 'Min',
    'countdown.seconds': 'Sec',
    'countdown.discount': '10% Extra OFF',
    'form.title': 'Request Free Trial',
    'form.subtitle': 'Special offer for expo visitors! Apply now and get a ',
    'form.subtitle_highlight': '10% discount coupon',
    'form.subtitle_end': '',
    'form.name': 'Name *',
    'form.email': 'Email *',
    'form.phone': 'Phone *',
    'form.purpose': 'Purpose',
    'form.purpose_personal': 'Personal Practice',
    'form.purpose_business': 'Business Purchase',
    'form.purpose_school': 'School/Education',
    'form.purpose_golf': 'Golf Club/Range',
    'form.interest': 'Interests (Multiple)',
    'form.interest_discount': 'Discount Info',
    'form.interest_catalog': 'Catalog',
    'form.interest_demo': 'Free Trial',
    'form.interest_newsletter': 'Newsletter',
    'form.message': 'Message',
    'form.privacy': 'I agree to the collection and use of personal information',
    'form.submit': '✨ Submit',
    'form.success': '✅ Application submitted! We will contact you soon.',
    'about.title': 'The PUTTIST Story',
    'about.origin_title': 'Where It All Began',
    'about.origin_text': 'Puttist was born in 2010 after reading The Putting Bible by the legendary Dave Pelz. One part stood out: the emphasis on distance control—how mastering that one skill could completely change your game. That idea sparked a mission: to make high-quality putting practice easier and more accessible for amateur golfers everywhere.',
    'about.philosophy_title': 'Digital Putting Meter',
    'about.philosophy_text': 'The PUTTIST is not a digital putting practice tool, but a digital "putting meter". We redefine the stereotype that "putting practice should be done on the actual green." Practice on actual greens with constantly changing speeds is a difficult and time-consuming classical method. With PUTTIST, tour-level putting practice is possible at home, in the office, anytime, anywhere.',
    'about.innovation_title': 'PUTTIST II Innovation',
    'about.feature1_title': 'Premium White Design',
    'about.feature1_desc': 'Luxurious white body and display for a refined look',
    'about.feature2_title': 'Enhanced Laser Function',
    'about.feature2_desc': 'LASER READY function enhances directional practice',
    'about.feature3_title': 'Extended to 20 Meters',
    'about.feature3_desc': 'Measuring distance extended from 15m to 20m. Now solve 3-putts from 20 meters!',
    'about.feature4_title': 'USB C-Type Charging',
    'about.feature4_desc': 'Uses USB C-type instead of dedicated charger. No problem if charger breaks!',
    'about.feature5_title': '9 Random Missions',
    'about.feature5_desc': 'Added 9 random missions up to 20 meters. Ultimate difficulty challenge!',
    'about.feature6_title': '60-Foot Practice at Home',
    'about.feature6_desc': 'Practice 60-foot long putts in your living room with just one ball. No ball return needed!',
    'features.title': 'Key Features',
    'features.subtitle': 'Professional-level putting training at home',
    'features.distance_title': '20m Distance Measurement',
    'features.distance_desc': 'Precise distance measurement up to 20 meters. Train in the same environment as real fields.',
    'features.width_title': '1m Width Measurement',
    'features.width_desc': 'Accurately detects up to 1 meter width. Get instant feedback to improve accuracy.',
    'features.portable_title': 'Portability',
    'features.portable_desc': 'Easy to set up and use anytime, anywhere. At home, office, or outdoors.',
    'technology.title': 'Scientific Training Unlike Traditional Putting Mats',
    'technology.subtitle': 'Perfect your putting with laser guide technology',
    'technology.precision_title': '✨ Laser Precision',
    'technology.precision_desc': 'Accurate measurement down to millimeters with advanced laser technology',
    'technology.data_title': '📊 Data Analysis',
    'technology.data_desc': 'Record and analyze all putting data to track skill improvement',
    'technology.feedback_title': '🎯 Instant Feedback',
    'technology.feedback_desc': 'Check putting results in real-time and correct immediately',
    'technology.pro_title': '🏆 Pro Training',
    'technology.pro_desc': 'Scientific training methods used by professional golfers',
    'demo.title': 'Watch PUTTIST II in Action',
    'demo.subtitle': 'Check out product usage and features through video',
    'cta.title': 'Improve Your Putting Skills with PUTTIST II Now',
    'cta.subtitle': 'Start professional-level training at home',
    'cta.button_naver': 'Buy Now (Naver)',
    'cta.button_amazon': 'Buy on Amazon',
    // FAQ Section
    'faq.title': 'Frequently Asked Questions',
    'faq.subtitle': 'Find answers to common questions about PUTTIST II',
    'faq.q1': 'What is PUTTIST II?',
    'faq.a1': 'PUTTIST II is a digital putting meter utilizing laser guide technology. It precisely measures distances up to 20m and widths up to 1m, allowing you to practice putting like a pro at home.',
    'faq.q2': 'What is the best putting trainer for home use?',
    'faq.a2': 'PUTTIST II is recommended. It offers 20m distance measurement, laser guidance, USB-C charging, and 9 random missions for effective indoor putting practice.',
    'faq.q3': 'How much does PUTTIST II cost?',
    'faq.a3': 'PUTTIST II Premium is 199,000 KRW and Standard is 159,000 KRW. Available on Naver Smart Store with free shipping.',
    'faq.q4': 'Does it really improve putting skills?',
    'faq.a4': 'Yes, the laser guide helps you aim accurately, and the distance measurement function allows you to practice consistent strokes, which is very effective for skill improvement.',
    'faq.q5': 'Is it difficult to set up?',
    'faq.a5': 'No installation required. Just take it out of the box and turn it on. With USB-C charging, 4 hours of charging provides 1 month of use.',
    'faq.q6': 'Can beginners use it?',
    'faq.a6': 'Yes, it is especially recommended for beginners. The laser guide line shows the accurate putting direction, and the distance measurement provides real-time feedback.',
    'faq.q7': 'Is it noisy for apartment use?',
    'faq.a7': 'Designed for quiet operation, you can use it without worrying about noise between floors. Practice quietly on any putting mat.',
    'faq.q8': 'How long does shipping take?',
    'faq.a8': 'Free delivery within 2-3 days after ordering. Shipment tracking is available when ordering through Naver Smart Store.',
    'faq.q9': 'Are refunds or returns possible?',
    'faq.a9': 'We offer a 30-day satisfaction guarantee. If you are not satisfied with the product, we will provide a 100% refund within 30 days.',
    'faq.q10': 'How do I get after-sales service?',
    'faq.a10': 'We provide 1 year of free after-sales service. Contact our customer service (010-1234-5678) for prompt assistance.'
  },
  ja: {
    'nav.features': '特徴',
    'nav.technology': '技術',
    'nav.about': '概要',
    'nav.contact': 'お問い合わせ',
    'nav.buy': '購入する',
    'hero.title': 'PUTTIST II',
    'hero.subtitle': 'デジタルパッティング練習の新基準',
    'hero.description': '従来のパッティングマットとは異なる科学的トレーニングシステム。レーザーガイド技術で20mの距離と1mの幅を正確に測定します。',
    'hero.learn_more': '詳しく見る',
    'hero.watch_demo': 'デモを見る',
    'share.kakao': 'カカオトークで共有',
    'countdown.title': '博覧会特別割引実施中',
    'countdown.label': '残り時間:',
    'countdown.days': '日',
    'countdown.hours': '時間',
    'countdown.minutes': '分',
    'countdown.seconds': '秒',
    'countdown.discount': '10%追加割引',
    'form.title': '無料体験お申し込み',
    'form.subtitle': '展示会来場者特別特典！今お申し込みで',
    'form.subtitle_highlight': '10%割引クーポン',
    'form.subtitle_end': 'プレゼント',
    'form.name': 'お名前 *',
    'form.email': 'メールアドレス *',
    'form.phone': '電話番号 *',
    'form.purpose': '利用目的',
    'form.purpose_personal': '個人練習用',
    'form.purpose_business': '法人購入',
    'form.purpose_school': '学校/教育機関',
    'form.purpose_golf': 'ゴルフ場/練習場',
    'form.interest': '関心情報（複数選択可）',
    'form.interest_discount': '割引情報',
    'form.interest_catalog': 'カタログ受取',
    'form.interest_demo': '無料体験申込',
    'form.interest_newsletter': 'ニュースレター購読',
    'form.message': 'お問い合わせ内容',
    'form.privacy': '個人情報の収集と利用に同意します',
    'form.submit': '✨ 送信',
    'form.success': '✅ お申し込みが完了しました！間もなくご連絡いたします。',
    'about.title': 'PUTTISTストーリー',
    'about.origin_title': 'はじまり',
    'about.origin_text': 'PUTTISTは2010年、伝説的なDave Pelzの「The Putting Bible」を読んで始まりました。特に印象的だったのは距離コントロールの重要性—その一つのスキルをマスターすることがゲームを完全に変えられるということです。そのアイデアが使命を生み出しました：世界中のアマチュアゴルファーのために、高品質なパッティング練習をより簡単でアクセスしやすくすること。',
    'about.philosophy_title': 'デジタルパッティングメーター',
    'about.philosophy_text': 'PUTTISTはデジタルパッティング練習機ではなく、デジタル「パッティングメーター」です。「パッティング練習は実際のグリーンで行うべき」という固定観念を再定義します。刻々と変化するグリーンスピードでの練習は難しく時間がかかる古典的な方法です。PUTTISTがあれば、自宅でもオフィスでも、いつでもどこでもツアーレベルのパッティング練習が可能です。',
    'about.innovation_title': 'PUTTIST IIイノベーション',
    'about.feature1_title': 'プレミアムホワイトデザイン',
    'about.feature1_desc': '高級感のあるホワイトボディとディスプレイで生まれ変わったPUTTIST',
    'about.feature2_title': 'レーザー機能強化',
    'about.feature2_desc': 'LASER READY機能で方向練習をさらに強化',
    'about.feature3_title': '20メートルに拡張',
    'about.feature3_desc': '15メートルから20メートルに測定距離拡張。20メートルの3パットも解決！',
    'about.feature4_title': 'USB C-タイプ充電',
    'about.feature4_desc': '専用充電器の代わりにUSB C-タイプを使用。充電器が故障しても大丈夫！',
    'about.feature5_title': '9つのランダムミッション',
    'about.feature5_desc': '20メートルまでの9つのランダムミッション追加。最高難易度のチャレンジ！',
    'about.feature6_title': '自宅で60フィート練習',
    'about.feature6_desc': 'ボール1個でリビングルームで60フィートのロングパット練習可能。ボールリターン不要！',
    'features.title': '主な機能',
    'features.subtitle': 'プロレベルのパッティング訓練を自宅で',
    'features.distance_title': '20m距離測定',
    'features.distance_desc': '最大20メートルまで精密な距離測定が可能です。実際のフィールドと同じ環境でトレーニングしましょう。',
    'features.width_title': '1m幅測定',
    'features.width_desc': '1メートル幅まで正確に検知します。精度向上のための即座のフィードバックを受け取ります。',
    'features.portable_title': '持ち運びやすさ',
    'features.portable_desc': 'いつでもどこでも簡単に設置して使用できます。自宅、オフィス、屋外どこでも可能です。',
    'technology.title': '従来のパッティングマットとは異なる科学的トレーニング',
    'technology.subtitle': 'レーザーガイド技術で完璧なパッティングを完成させましょう',
    'technology.precision_title': '✨ レーザー精度',
    'technology.precision_desc': '最先端レーザー技術でミリメートル単位まで正確な測定',
    'technology.data_title': '📊 データ分析',
    'technology.data_desc': 'すべてのパッティングデータを記録・分析してスキル向上を追跡',
    'technology.feedback_title': '🎯 即座のフィードバック',
    'technology.feedback_desc': 'リアルタイムでパッティング結果を確認して即座に修正',
    'technology.pro_title': '🏆 プロトレーニング',
    'technology.pro_desc': 'プロゴルファーが使用する科学的トレーニング方法',
    'demo.title': '動画で見るPUTTIST II',
    'demo.subtitle': '製品の使用方法と特徴を動画で確認してください',
    'cta.title': '今すぐPUTTIST IIでパッティング技術を向上させましょう',
    'cta.subtitle': 'プロレベルのトレーニングを自宅で始めましょう',
    'cta.button_naver': '今すぐ購入（Naver）',
    'cta.button_amazon': 'Amazonで購入',
    // FAQ Section
    'faq.title': 'よくある質問',
    'faq.subtitle': 'PUTTIST IIについてよくある質問をご確認ください',
    'faq.q1': 'PUTTIST IIはどんな製品ですか？',
    'faq.a1': 'PUTTIST IIはレーザーガイド技術を活用したデジタルパッティングメーターです。20mの距離と1mの幅を精密に測定し、自宅でプロのようにパッティング練習ができます。',
    'faq.q2': '自宅で使うのに最適なパッティング練習器は？',
    'faq.a2': 'PUTTIST IIがおすすめです。20m距離測定、レーザーガイド、USB-C充電、9種類のランダムミッションで効果的な室内パッティング練習が可能です。',
    'faq.q3': 'PUTTIST IIの価格はいくらですか？',
    'faq.a3': 'PUTTIST II高級版は199,000ウォン、一般版は159,000ウォンです。Naverスマートストアで購入可能で、送料無料です。',
    'faq.q4': 'パッティングスキル向上に効果がありますか？',
    'faq.a4': 'はい、レーザーガイドで正確な方向を確認し、距離測定機能で一貫したストロークを練習できるため、スキル向上に非常に効果的です。',
    'faq.q5': '設置は難しくないですか？',
    'faq.a5': '設置不要です。箱から出して電源を入れるだけですぐに使えます。USB-C充電で4時間の充電で1ヶ月使用可能です。',
    'faq.q6': '初心者でも使えますか？',
    'faq.a6': 'はい、特に初心者におすすめです。レーザーガイドラインが正確なパッティング方向を示し、距離測定機能がリアルタイムでフィードバックを提供します。',
    'faq.q7': 'マンションで使っても騒音は気になりませんか？',
    'faq.a7': '静音設計で階間騒音の心配なく使用できます。パッティングマットの上で静かに練習できます。',
    'faq.q8': '配送にはどのくらいかかりますか？',
    'faq.a8': '注文後2-3日以内に無料配送されます。Naverスマートストアで注文時、配送追跡が可能です。',
    'faq.q9': '返金や返品は可能ですか？',
    'faq.a9': '30日間満足保証制度を運営しています。製品にご満足いただけない場合、30日以内に100%返金いたします。',
    'faq.q10': 'アフターサービスはどのように受けられますか？',
    'faq.a10': '1年間無料アフターサービスを提供しています。カスタマーサービス(010-1234-5678)にご連絡いただければ迅速に対応いたします。'
  },
  zh: {
    'nav.features': '特点',
    'nav.technology': '技术',
    'nav.about': '关于',
    'nav.contact': '联系我们',
    'nav.buy': '立即购买',
    'hero.title': 'PUTTIST II',
    'hero.subtitle': '数字推杆练习的新标准',
    'hero.description': '与传统推杆垫不同的科学训练系统。采用激光引导技术精确测量20米距离和1米宽度。',
    'hero.learn_more': '了解更多',
    'hero.watch_demo': '观看演示',
    'share.kakao': '分享到KakaoTalk',
    'countdown.title': '博览会特别折扣进行中',
    'countdown.label': '剩余时间:',
    'countdown.days': '天',
    'countdown.hours': '小时',
    'countdown.minutes': '分钟',
    'countdown.seconds': '秒',
    'countdown.discount': '额外10%折扣',
    'form.title': '申请免费试用',
    'form.subtitle': '展会访客特别优惠！现在申请可获得',
    'form.subtitle_highlight': '10%折扣券',
    'form.subtitle_end': '',
    'form.name': '姓名 *',
    'form.email': '电子邮件 *',
    'form.phone': '电话 *',
    'form.purpose': '使用目的',
    'form.purpose_personal': '个人练习',
    'form.purpose_business': '企业采购',
    'form.purpose_school': '学校/教育机构',
    'form.purpose_golf': '高尔夫球场/练习场',
    'form.interest': '感兴趣的信息（可多选）',
    'form.interest_discount': '折扣信息',
    'form.interest_catalog': '目录下载',
    'form.interest_demo': '免费试用',
    'form.interest_newsletter': '订阅新闻',
    'form.message': '留言',
    'form.privacy': '我同意收集和使用个人信息',
    'form.submit': '✨ 提交',
    'form.success': '✅ 申请已提交！我们会尽快联系您。',
    'about.title': 'PUTTIST故事',
    'about.origin_title': '起源',
    'about.origin_text': 'PUTTIST诞生于2010年，源于阅读传奇人物Dave Pelz的《The Putting Bible》。其中特别引人注目的部分是：对距离控制的强调——掌握这一技能可以完全改变你的比赛。这个想法激发了一个使命：让世界各地的业余高尔夫球手更容易接触到高质量的推杆练习。',
    'about.philosophy_title': '数字推杆测量仪',
    'about.philosophy_text': 'PUTTIST不是数字推杆练习工具，而是数字"推杆测量仪"。我们重新定义了"推杆练习应该在实际果岭上进行"的固定观念。在速度不断变化的实际果岭上练习是一种困难且耗时的传统方法。有了PUTTIST，您可以在家中、办公室，随时随地进行巡回赛水平的推杆练习。',
    'about.innovation_title': 'PUTTIST II创新',
    'about.feature1_title': '高级白色设计',
    'about.feature1_desc': '豪华的白色机身和显示屏，全新的PUTTIST',
    'about.feature2_title': '激光功能增强',
    'about.feature2_desc': 'LASER READY功能进一步增强方向练习',
    'about.feature3_title': '扩展至20米',
    'about.feature3_desc': '测量距离从15米扩展到20米。现在20米三推也能解决！',
    'about.feature4_title': 'USB C型充电',
    'about.feature4_desc': '使用USB C型代替专用充电器。充电器坏了也没关系！',
    'about.feature5_title': '9个随机任务',
    'about.feature5_desc': '增加了最高20米的9个随机任务。终极难度挑战！',
    'about.feature6_title': '在家练习60英尺',
    'about.feature6_desc': '只用一个球就可以在客厅练习60英尺长推。无需球回收！',
    'features.title': '核心功能',
    'features.subtitle': '在家进行职业水平的推杆训练',
    'features.distance_title': '20米距离测量',
    'features.distance_desc': '可精确测量最远20米的距离。在与实际场地相同的环境中训练。',
    'features.width_title': '1米宽度测量',
    'features.width_desc': '可精确检测1米宽度。获得即时反馈以提高准确度。',
    'features.portable_title': '便携性',
    'features.portable_desc': '随时随地轻松安装和使用。家中、办公室、室外都可以。',
    'technology.title': '与传统推杆垫不同的科学训练',
    'technology.subtitle': '用激光引导技术完成完美推杆',
    'technology.precision_title': '✨ 激光精度',
    'technology.precision_desc': '采用先进激光技术进行毫米级精确测量',
    'technology.data_title': '📊 数据分析',
    'technology.data_desc': '记录和分析所有推杆数据以追踪技能提升',
    'technology.feedback_title': '🎯 即时反馈',
    'technology.feedback_desc': '实时确认推杆结果并立即纠正',
    'technology.pro_title': '🏆 专业训练',
    'technology.pro_desc': '职业高尔夫球手使用的科学训练方法',
    'demo.title': '视频展示PUTTIST II',
    'demo.subtitle': '通过视频确认产品使用方法和特点',
    'cta.title': '现在就用PUTTIST II提升推杆技术',
    'cta.subtitle': '在家开始专业级训练',
    'cta.button_naver': '立即购买（Naver）',
    'cta.button_amazon': '在Amazon购买',
    // FAQ Section
    'faq.title': '常见问题',
    'faq.subtitle': '查看关于PUTTIST II的常见问题',
    'faq.q1': 'PUTTIST II是什么产品？',
    'faq.a1': 'PUTTIST II是一款利用激光引导技术的数字推杆仪。精确测量20m距离和1m宽度，让您在家也能像职业选手一样练习推杆。',
    'faq.q2': '适合在家使用的推杆练习器是什么？',
    'faq.a2': '推荐PUTTIST II。20m距离测量、激光引导、USB-C充电、9种随机任务，让室内推杆练习更加高效。',
    'faq.q3': 'PUTTIST II的价格是多少？',
    'faq.a3': 'PUTTIST II高级版199,000韩元，普通版159,000韩元。可在Naver智能商店购买，免费配送。',
    'faq.q4': '对提高推杆技术有效吗？',
    'faq.a4': '是的，激光引导帮助您准确瞄准方向，距离测量功能让您练习一致的击球动作，对技能提升非常有效。',
    'faq.q5': '安装困难吗？',
    'faq.a5': '无需安装。从包装盒中取出并打开电源即可使用。USB-C充电，充电4小时可使用1个月。',
    'faq.q6': '初学者可以使用吗？',
    'faq.a6': '是的，特别推荐给初学者。激光引导线显示准确的推杆方向，距离测量功能提供实时反馈。',
    'faq.q7': '在公寓使用会有噪音吗？',
    'faq.a7': '静音设计，无需担心楼层间噪音。可以在推杆垫上安静地练习。',
    'faq.q8': '配送需要多长时间？',
    'faq.a8': '下单后2-3天内免费配送。通过Naver智能商店下单时可追踪配送。',
    'faq.q9': '可以退款或退货吗？',
    'faq.a9': '我们提供30天满意保证。如果您对产品不满意，30天内可获得100%退款。',
    'faq.q10': '如何获得售后服务？',
    'faq.a10': '我们提供1年免费售后服务。请联系客服(010-1234-5678)，我们将迅速处理。'
  }
};

const languageLabels = {
  ko: '🇰🇷 한국어',
  en: '🇺🇸 English',
  ja: '🇯🇵 日本語',
  zh: '🇨🇳 中文'
};

interface LanguageContextType {
  currentLanguage: string;
  changeLanguage: (lang: string) => void;
  t: (key: string) => string;
  languageLabels: typeof languageLabels;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState<string>(() => {
    return localStorage.getItem('puttist-language') || 'ko';
  });

  const changeLanguage = (lang: string) => {
    setCurrentLanguage(lang);
    localStorage.setItem('puttist-language', lang);
  };

  const t = (key: string): string => {
    return translations[currentLanguage]?.[key] || key;
  };

  useEffect(() => {
    changeLanguage(currentLanguage);
  }, []);

  return (
    <LanguageContext.Provider value={{ currentLanguage, changeLanguage, t, languageLabels }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};
